/* This file will be used to test how comments work */

/*
*
* Block Comment C/C++ Style
*
*/

// Single line C/C++ style

# Single line assembly style

@ Single line assembly style some assembly lauguages

addi    r0, /* Use stack point */ r1

li      r0, 0x450   # After instruction

cmp     r5, r6  // After instruction

subf     r0, // Some comment r2

mulli   r2, #Some comment r6

/*

add 

.section

*/

// add

# add

